apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: final
data:
  APP_COLOR: "pink"
  AWS_REGION: "us-east-1"
  MY_NAME: "Group 9"
  BG_IMAGE_URL: "s3://final-project-clo835-g9/pink.jpg"
  DBHOST: "mysql"
  DBPORT: "3306"
  DATABASE: "employees"
